version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  mpt_app:
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
